name: Test Multiple Python Versions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make install
      - name: Lint with pylint
        run: |
          make lint
      - name: Test with pytest
        run: |
          make test
      - name: Format code with Python Black
        run: |
          make format
      - name: run main python code
        run: |
          make run
      - name: deploy
        run: |
          make deploy

#      - name: Login to DockerHub Registry
#        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
#      - name: Set up Docker Buildx
#        id: buildx
#        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      #- uses: actions/checkout@v2
#      - name: Build the Docker image
#        run: docker build . --file Dockerfile --tag worldbosskafka/mathz:$(date +%s)
#
#      - name: Build the latest Docker image
#        run: docker build . --file Dockerfile --tag worldbosskafka/mathz:latest


      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mathz:latest

      #- uses: actions/checkout@v3
#      - name: Publish to Registry
#        uses: elgohr/Publish-Docker-Github-Action@v4
#        with:
#          name: worldbosskafka
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#          dockerfile: Dockerfile

      - name: Push the latest Docker image
        run: docker push worldbosskafka/mathz:$(date +%s)
